services:
  db:
    image: postgis/postgis:15-3.4
    container_name: fpts-postgis
    environment:
      POSTGRES_DB: fpts
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./src/fpts/sql:/docker-entrypoint-initdb.d:ro

volumes:
  db_data:
